name: جمع‌آوری خودکار کانفیگ VLESS

on:
  workflow_dispatch:  # امکان اجرا دستی
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت یکبار

jobs:
  fetch-configs:
    runs-on: ubuntu-latest
    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: نصب وابستگی‌ها
        run: |
          pip install -r requirements.txt

      - name: ایجاد فایل session (اگر session رمزگذاری شده وجود داشت)
        if: success()
        run: |
          echo "Checking for encrypted session..."
          if [ -f session.session.enc ]; then
            python -c "
import os
from cryptography.fernet import Fernet
key = os.getenv('SESSION_DECRYPT_KEY').encode()
with open('session.session.enc', 'rb') as f:
    data = f.read()
cipher = Fernet(key)
decrypted = cipher.decrypt(data)
with open('session.session', 'wb') as f:
    f.write(decrypted)
print('✅ session.session از حالت رمزگذاری خارج شد.')
"
          else
            echo "⚠️ فایل session.session.enc یافت نشد. اولین اجرا ممکن است نیاز به ورود داشته باشد."
          fi

      - name: اجرای اسکریپت جمع‌آوری
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE: ${{ secrets.PHONE }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_BRANCH: ${{ secrets.GH_BRANCH }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_FILE_PATH: ${{ secrets.GH_FILE_PATH }}
          CHANNELS: ${{ secrets.CHANNELS }}
        run: python fetch_configs.py
